CREATE TABLE IF NOT EXISTS personajes (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(100) NOT NULL,
gender VARCHAR(10) NOT NULL,
ki FLOAT NOT NULL,
maxKi FLOAT NOT NULL,
description TEXT NOT NULL,
image VARCHAR(255) NULL,
affiliation VARCHAR(100) NOT NULL
);